version: '3.9'

services:
  fastapi:
    build: .
    restart: always
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql://user:password@database/tasks
    ports:
      - "8000:8000"

  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
